### PR TITLE
Merge branch '1.3' of ezsystems/ezplatform-content-forms into main

### PR DESCRIPTION
**Pull request by ezrobot**
Cross merge PR

### CODE REVIEW

**Review by konradoboza — APPROVED** [review]

**Review by webhdx — APPROVED** [review]

**Comment by webhdx** [comment]
@konradoboza It's okay but you need to resolve conflicts here & ping me to merge it.

**Comment by mateuszdebinski** [comment]
@webhdx done, config resolved

**Comment by ViniTou** [comment]
@mnocon @ibexa/quality-assurance 
I guess behat features needs to be rewriten to use ibexa config key, right?
https://github.com/ibexa/content-forms/tree/main/features

**Comment by mnocon** [comment]
@ViniTou changed in https://github.com/ibexa/content-forms/pull/16/commits/ee7ec656107383710478bdfcec8f77038edbe919 , tests are green now

**Pull request merged**
