### PR TITLE
IBX-3289: Fixed validation exception on nulled but required fields

### PR DESCRIPTION
**Pull request by Nattfarinn**
JIRA: https://issues.ibexa.co/browse/IBX-3289

### CODE REVIEW

**Review by Steveb-p — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]

**Review by adamwojs — COMMENTED** [review]
Test case for FieldValueValidator class would be very appreciated.

**Review by webhdx — APPROVED** [review]

**Comment by micszo** [comment]
Could someone confirm code style in unchanged files is out of scope?

**Comment by ViniTou** [comment]
@micszo 
They are and should be fixed in 3.3 and merged up. It comes from bug fixes made in cs fixer.

**Comment by micszo** [comment]
> @micszo
> They are and should be fixed in 3.3 and merged up. It comes from bug fixes made in cs fixer.

All clear, thanks!

**Review by micszo — CHANGES_REQUESTED** [review]
The fix covers missing Customer group but it does not cover missing Billing address.

**Comment by Nattfarinn** [comment]
@micszo fix for Billing Address (or FT Address in general) is covered in separate PR: https://github.com/ibexa/fieldtype-address/pull/7

**Review by micszo — APPROVED** [review]
Validation works fine now. 👍🏻

**Pull request merged**
